# Generated by Django 5.2.17 on 2026-09-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10, verbose_name='Statut')),
                ('seo_title', models.CharField(blank=True, help_text='Laisser vide pour utiliser le titre par défaut du réglage général.', max_length=70, verbose_name='Titre SEO')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='Image de partage (Open Graph)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('short_description', models.CharField(help_text="Affichée sur la page d'accueil (carte de service).", max_length=255, verbose_name='Description courte')),
                ('content', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône du set utilisé par le design system (défini en Phase 7).", max_length=50, verbose_name='Icône')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Service / Expertise',
                'verbose_name_plural': 'Services / Expertises',
                'ordering': ['order', 'title'],
            },
        ),
    ]
