# Generated by Django 5.2.17 on 2026-09-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BEFOPT', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('phone_1', models.CharField(blank=True, max_length=30)),
                ('phone_2', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Réglages du site',
                'verbose_name_plural': 'Réglages du site',
            },
        ),
    ]
