# Generated by Django 5.2.17 on 2026-09-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bp',
            field=models.CharField(blank=True, max_length=100, verbose_name='Boîte postale'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta description par défaut'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Image de partage par défaut (Open Graph)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_seo_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Titre SEO par défaut'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, help_text='Ex. : mention légale courte ou copyright. Laisser vide si non fourni.', max_length=255, verbose_name='Texte du footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_text',
            field=models.TextField(blank=True, verbose_name='Texte de mission'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='X / Twitter'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail de contact'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_1',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone principal'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone secondaire'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, help_text="Ex. : Connecter le talent d'aujourd'hui aux technologies de pointe de demain.", max_length=255, verbose_name='Slogan / accroche'),
        ),
    ]
