# Generated by Django 5.2.17 on 2026-09-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10, verbose_name='Statut')),
                ('seo_title', models.CharField(blank=True, help_text='Laisser vide pour utiliser le titre par défaut du réglage général.', max_length=70, verbose_name='Titre SEO')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og/', verbose_name='Image de partage (Open Graph)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.CharField(help_text='Affichée dans la liste des formations.', max_length=255, verbose_name='Description courte')),
                ('content', models.TextField(blank=True, verbose_name='Contenu détaillé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/', verbose_name='Image')),
                ('image_alt_text', models.CharField(blank=True, help_text="Décrit l'image pour l'accessibilité (obligatoire si une image est ajoutée).", max_length=200, verbose_name="Texte alternatif de l'image")),
                ('published_at', models.DateTimeField(blank=True, help_text='Utilisée pour trier les formations. Laisser vide pour utiliser la date de création.', null=True, verbose_name='Date de publication')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
